### ISSUE TITLE
APK Release

### ISSUE THREAD

**Issue by RobinFrcd** [NeoAren/virtualtag#23]
Hi,
Would it be possible to release the APK ? At least on GitHub, F-Droid would be a great nice to have !

Thanks

**Comment by andras-adam** [comment]
Hey, thanks for your interest in the project! I made a release now that has the APK.

**Comment by RobinFrcd** [comment]
Thank you so much !

I was also wondering, is it possible to use a VirtualTag as a real NFC card ?

Thanks again

**Comment by andras-adam** [comment]
That was our original plan too! Unfortunately the Android OS doesn't allow for making applications like that for security reasons, as legally speaking it would be considered as forgery. There actually is a feature in Android called [host-based card emulation](https://developer.android.com/guide/topics/connectivity/nfc/hce) which allows you to use your phone as a keycard, but it will only work with keycard readers whose unique identifiers you hardcode into the app. So it would work if let's say you are deploying a keycard infrastructure in an office and make an app for it yourself so employees don't need to carry around cards, but it will not be possible to scan just any card and emulate them.

**Comment by RobinFrcd** [comment]
Alright, thank you very much for the crystal clear answer ! 🙏
